on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  LAMBDA_FUNCTION_NAME: UDEL-Health-Check
  LAMBDA_LAYER_NAME1: Selenium
  LAMBDA_LAYER_NAME2: Chromedriver
  LAMBDA_RUNTIME: python3.9

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpoppler-cpp-dev pkg-config python-dev
          pip install --target=python boto3
      # from: mariamrf/py-lambda-action
      - name: install_selenium_zip_dependencies
        run: |
          echo "Installing and zipping dependencies..."
          mkdir -p python
          pip install --target=python -r requirements.txt
          zip -r dependencies.zip ./python
      - name: publish_dependencies_as_selenium_layer
        run: |
          echo "Publishing dependencies as selenium layer..."
          result=$(aws lambda publish-layer-version --layer-name "${LAMBDA_LAYER_NAME1}" --zip-file fileb://dependencies.zip)
          echo $result
          LAYER_VERSION_ARN=$(jq '.LayerVersionArn' <<< "$result")
          rm -rf python
          rm dependencies.zip
      - name: install_chrome_zip_dependencies
        run: |
          echo "Installing and zipping dependencies..."
          mkdir -p chromedriver
          cd chromedriver
          curl -SL https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip > chromedriver.zip
          unzip chromedriver.zip
          rm chromedriver.zip
          curl -SL https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-41/stable-headless-chromium-amazonlinux-2017-03.zip > headless-chromium.zip
          unzip headless-chromium.zip
          rm headless-chromium.zip
          ls
          zip -r chromedriver.zip chromedriver headless-chromium
      - name: publish_dependencies_as_chrome_layer
        run: |
          echo "Publishing dependencies as chrome layer..."
          result=$(aws lambda publish-layer-version --layer-name "${LAMBDA_LAYER_NAME2}" --zip-file fileb://chromedriver.zip)
          echo $result
          LAYER_VERSION_ARN=$(jq '.LayerVersionArn' <<< "$result")
          rm -rf python
          rm chromedriver.zip
      - name: publish_function_code
        run: |
          echo "Deploying the code itself..."
          zip -r code.zip . -x \*.git\*
          aws lambda update-function-code --function-name "${LAMBDA_FUNCTION_NAME}" --zip-file fileb://code.zip