name: Python package
on:
  push:
    branches:
      - master

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run HealthCheck
        run: |
          python3 HealthCheck.py